knpu_oauth2_client:
    clients:
        google:
            type: google
            client_id: '%env(OAUTH_GOOGLE_ID)%'
            client_secret: '%env(OAUTH_GOOGLE_SECRET)%'
            redirect_route: connect_google_check
            redirect_params: {}

        facebook:
            type: facebook
            client_id: '%env(OAUTH_FACEBOOK_ID)%'
            client_secret: '%env(OAUTH_FACEBOOK_SECRET)%'
            redirect_route: connect_facebook_check
            redirect_params: {}
            graph_api_version: v21.0

        apple:
            type: apple
            client_id: '%env(OAUTH_APPLE_SERVICES_ID)%'
            team_id: '%env(OAUTH_APPLE_TEAM_ID)%'
            key_file_id: '%env(OAUTH_APPLE_KEY_ID)%'
            key_file_path: '%env(OAUTH_APPLE_KEY_PATH)%'
            redirect_route: connect_apple_check
            redirect_params: {}
